---
- hosts: TET2
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
   - name: send command to host
     zos_operator:
      cmd: 'd r,r'
     register: result
   - name: response
     debug:
      msg:  "{{ result }}"
   - local_action: 
     copy:
      content: "{{ result }}"
      dest: file
#     ={{ result }} dest=file
# 
#   - name: save output from local cmd to local directory
#     copy:
#       content: "{{ result  | replace('\\n', '\n') }}"
#       dest: "/etc/ansible/output/{{ inventory_hostname }}.ios"
      
