---
- name: OS family
  hosts: localhost
  tasks:
    - name: print OS Family
      debug: var=ansible_os_family     
    - name: save output to local directory
      copy:
        content: "{{ ansible_os_family }}"           
        dest: "etc/ansible/output/{{ inventory_hostname }}.ios"
...
