---
- name: OS family
  hosts: localhost
  tasks:
    - name: print OS Family
      debug: var=ansible_os_family
      
- name: save output to local directory
  ansible.builtin.copy:
    content: "{{ ansible_os_family.stdout | replace('\\n', '\n') }}"           
    dest: "show-output/{{ inventory_hostname }}.ios"
...
