###############################################################################
# Copyright (c) IBM Corporation 2020
###############################################################################

###############################################################################
# This sample playbook demonstrates using various modules included in the
# Red Hat Ansible Certified Content for IBM Z core collection.
#
# Usage:
#  ansible-playbook -i <inventory> <playbook>
#
# Example:
#  ansible-playbook -i inventory zos-collection-sample.yaml
#
###############################################################################

---
- hosts: TET2
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: Ensure JCL folder exists to hold JCL
      file:
        path: /tmp/ansible/jcl
        state: directory
        
    - name: Copy a local binary file to a PDSE member
      zos_copy:
        src: /etc/ansible/playbooks/files/WWZ038.GSD##E1.FSA101.DUMPTERS.D030320.BIN
        dest: WWZ038.GSD##E1.FSA101.DUMPTERS.D030320.BIN
        is_binary: true





