---
- hosts: TET2
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
    - name: issue shell command
      shell: dls -l 'PL25816.*'
      register: result
    - name: response
      debug:
        msg: " {{ result }} "
