---
- hosts: all
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"

  tasks:
#    # Ping the host
#    - name: Ping host - {{ inventory_hostname }}
#      ping:
#      register: result
     - name: define zfs
       shell: "zfsadm define -aggregate OMVS.PRDS.ZOAU.ZFS -cylinders 50 50"
       register: result
       changed_when: true
   
