---
- hosts: TET2
  collections:
    - ibm.ibm_zos_core
  gather_facts: no
  environment: "{{ environment_vars }}"
  tasks:
   - name: send command to host
     zos_operator:
      cmd: 'd r,r'
     register: result
   - name: response
     debug:
      msg:  "{{ result }}"
      
